# Generated by Django 2.0.3 on 2018-03-23 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='breed',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='pet',
            name='species',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
