# Generated by Django 2.0.3 on 2018-03-23 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0002_auto_20180322_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='submssion_date',
        ),
        migrations.AddField(
            model_name='pet',
            name='submission_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='name',
            field=models.CharField(max_length=1),
        ),
    ]
